### ISSUE TITLE
mention that input in the graylog server should be gelf udp

### ISSUE THREAD

**Issue by treaz** [Moocar/logback-gelf#47]
Great plugin :+1: 

It would be really useful if somewhere in readme.md you'd mention that logback-gelf creates upd gelf messages. I had to look in the sourcecode and figure out that it's creating datagrams and I should configure the graylog server to listen to upd (create a gelf upd input).

**Comment by Moocar** [comment]
Yep, I'm working on a new version where TCP is supported as well so I'll make it clear as part of that release. Back in my day, graylog only supported UDP ;)

**Comment by mundrusatish** [comment]
Greetings,

It helps me to sent messages for Graylog udp inputs. As said, let us know if it covered the TCP and TCP over SSL inputs.

Thanks in advance.

~Regards

**Comment by Moocar** [comment]
Here's the branch that I'm working on. In this new flow, Adding an SSL TCP appender should be pretty easy. I probably won't include one on the first release, but you're welcome to create a PR once this is release.

https://github.com/Moocar/logback-gelf/tree/the-great-appender-rejig

**Comment by Moocar** [comment]
I just finished the branch, any chance you'd be interested in testing it @treaz and @mundrusatish? I've done a fair bit, but it would be great to get some feedback on the new approach. You'll need to build both socket-encoder-appender and logback-gelf from scratch as they're not on maven central yet

https://github.com/Moocar/socket-encoder-appender
https://github.com/Moocar/logback-gelf/tree/the-great-appender-rejig

**Comment by treaz** [comment]
Sorry Anthony, I'm already caught up with another project and I don't have any more time to play with graylog.

**Comment by Moocar** [comment]
version 2.0beta1 with UDP and TCP support is now released. Closing this issue.
