### ISSUE TITLE
mvn build fails with unresolved dependency com.stuartsierra:component

### ISSUE THREAD

**Issue by e-tothe-ipi** [Moocar/logback-gelf#50]
This issue pertains to 0.2beta1.

Assuming you want to keep compatibility with using plain vanilla maven central. 

Out of the box, it cannot be built because the following dependencies are not in maven central:

[ERROR] Failed to execute goal on project logback-gelf: Could not resolve dependencies for project me.moocar:logback-gelf:jar:0.2beta2-SNAPSHOT: The following artifacts could not be resolved: com.stuartsierra:component:jar:0.2.3, org.mockito:mockito-core:jar:1.10.9: Failure to find com.stuartsierra:component:jar:0.2.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

org.mockito:mockito-core:jar:1.10.9 is an easy fix... I just replaced it with 1.10.19.
com.stuartsierra:component:jar:0.2.3 is not in maven central, but rather in clojars or something.

Maybe you can add a section to the readme on how you have maven set up to get the build to succeed?

**Comment by Moocar** [comment]
I just added clojars as a repository which fixes this issue. Thanks.

**Comment by e-tothe-ipi** [comment]
Yeah build works great now.
