### ISSUE TITLE
no colons supported in property values

### ISSUE THREAD

**Issue by roomsg** [Moocar/logback-gelf#55]
would be nice to be able to have properties with colons (":") in it (eg: url).

Currrently not supported (v0.12), IllegalArgumentException is thrown:
"staticAdditionalField must be of the format key:value, where key is the additional field key (therefore should have a leading underscore), and value is a static string. e.g. _node_name:www013"

**Comment by Moocar** [comment]
Agreed. The hack would be to split on the first \: but I'm thinking that explicit </key> </value> fields will be more future proof.

**Comment by Moocar** [comment]
@roomsg mind checking out and reviewing PR #57 ? Hopefully it solves this problem for you.

**Comment by roomsg** [comment]
Thx, will do a quick review of https://github.com/Moocar/logback-gelf/pull/57

**Comment by Moocar** [comment]
Solved in #57
