### ISSUE TITLE
Error initializing static fields

### ISSUE THREAD

**Issue by muuki88** [Moocar/logback-gelf#62]
Hi,

I'm using the template from the _README.md_, but my logger fails to initialize the static fields. The error message is:

```
-ERROR in ch.qos.logback.core.joran.spi.Interpreter@38:66 - no applicable action for [staticField], current ElementPath  is [[configuration][appender][encoder][layout][staticField]]
-ERROR in ch.qos.logback.core.joran.spi.Interpreter@39:24 - no applicable action for [key], current ElementPath  is [[configuration][appender][encoder][layout][staticField][key]]
-ERROR in ch.qos.logback.core.joran.spi.Interpreter@40:26 - no applicable action for [value], current ElementPath  is [[configuration][appender][encoder][layout][staticField][value]]
```

The fields are not available in graylog2.

part of my `prod-logger.xml`

```xml
<appender name="GELF UDP APPENDER" class="me.moocar.logbackgelf.GelfUDPAppender">
   ...
   <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
      <layout class="me.moocar.logbackgelf.GelfLayout">
         ...
         <staticField class="me.moocar.logbackgelf.Field">
            <key>_environment</key>
            <value>prod</value>
         </staticField>
      </layout>
   </encoder>
</appender>
```

My library dependencies

- `"ch.qos.logback" % "logback-core" % "1.1.2"`
- `"ch.qos.logback" % "logback-classic" % "1.1.2"`
- `"org.slf4j" % "slf4j-api" % "1.7.6"`
- `"me.moocar" % "logback-gelf" % "0.2"`

**Comment by muuki88** [comment]
I build a snapshot version myself and now things work.

**Comment by kidpollo** [comment]
Same problem here!

**Comment by kidpollo** [comment]
@muuki88 can you re-open the issue it stil is not resolved

**Comment by kidpollo** [comment]
Ugh nvm I see that the Readme updated but there has not been a release with this change yet

**Comment by kedgecomb** [comment]
Any ETA on a release with this fix in it?

**Comment by Moocar** [comment]
Sorry everyone. I've been terrible on this. I haven't used Java or Graylog for 4 years now so my interest in maintaining this project is almost non existent. If anyone is keen on taking over, I'd be more than happy to transfer it over. In the meantime, I'll create a release now.

**Comment by Moocar** [comment]
Done. Should be up in maven central in 2 hours

**Comment by muuki88** [comment]
np @Moocar thx for the release. We should search on twitter for a maintainer :)

**Comment by Moocar** [comment]
Done :) https://twitter.com/Moocar/status/690036974531547136

**Comment by kedgecomb** [comment]
Yup, thanks for the release - works great.  Sorry to see you go!

**Comment by Purna2008** [comment]
HI, is there any new release for the additionalField fix please?

**Comment by Moocar** [comment]
@Purna2008 as per the README, I'm not supporting this project anymore so there won't be anymore releases.
